import re
import datetime


def print_messages(messages, target):
    """
    print messages that were sent by a person (by target letter)
    """
    count = 0
    for message in messages[::-1]:
        if message["sender_name"][0] == target:
            print(message["content"])
            count += 1
    print(count)


def dput(d, key):
    """
    increment the count of the value at the specific key, or create a new key
    """
    if key in d:
        d[key] += 1
    else:
        d[key] = 1


def filter_msg(msg):
    """
    helper to remove messages that were autogenerated
    return None if autogenerated
    """
    content = msg["content"]
    if content in [
        "You are now connected on Messenger.",
        "You sent an attachment."] or \
        re.match("You sent [0-9|a]{1,2} photos?", content) or \
        re.match("http", content):
        return None
    return msg


def to_time(ms_stamp):
    """
    take a 13 digit timestamp in ms and convert to a date time object
    """
    return datetime.datetime.fromtimestamp(ms_stamp // 1000)

def get_time(msg):
    """
    get the time from a message
    """
    timestamp = msg["timestamp_ms"]
    time = to_time(timestamp)
    return time
